# Configuration file in YAML format
#
#
# Processing configs
process:
  
  # verbose mode (normal/debugger)
  verbose: normal

# administrative information
admin:

  author: 'IGS AC Coordinator'
  contact: 'acc@igs.org'

# Orbit combination configs
orbits:

  # Analysis center contributions
  ac_contribs:

    # weighted centers:
    weighted:
      systems:
        COD: [G,R,E]
        ESA: [G,R,E]
        GFZ: [G,R,E]
        GRG: [G,R,E]
        JPL: [G,R,E]
        MIT: [G,R,E]
        NGS: [G,R,E]
        TUG: [G,R,E]
        WHU: [G,R,E]
      prns:
      svns:

    # unweighted centers (for comparison only)
    unweighted:
      systems:
        IG2: [G]
        IG3: [G]
      prns:
      svns:

    # excluded centers
    excluded:
      systems:
      prns:
      svns:

  # solution (FIN/RAP/ULT)
  #solution: FIN

  # sampling rate (None or an integer in seconds)
  sampling: 900

  # root directory for orbit submissions
  subm_rootdir: /data/repro3/ac_subm_repro3

  # root directory for saving the products
  prod_rootdir: /data/repro3/products/IGS2R03GRE_15M

  # path to satellite metadata file
  sat_metadata_file: /data/repro3/metadata/igs_metadata_2114.snx

  # Earth orientation paramaters (EOP) source format
  # (IERS_EOP14_C04/IERS_EOP_rapid/IGS_ERP2/None)
  eop_format: IGS_ERP2

  # path to the EOP data
  eop_file: /data/repro3/metadata/igs_final.erp

  # center weighting method (global/by_constellation/by_block/by_sat)
  cen_wht_method: by_sat

  # satellite weighting method (RMS_L1)
  sat_wht_method: RMS_L1

  # Transform orbits to a same reference frame?
  # [Translations,Rotations,Scale]
  rf_align: [False,True,False]

  # Root directory for reference frame combination summary files
  # Needed for reference frame alignment
  rf_rootdir: /data/repro3/products/sinex

  # Reference frame summary file name identifier
  rf_name: IGS0R03SNX

  # Combination name/abbreviation (3 characters)
  cmb_name: IGS

  # Combination version/solution identifier (0 to 9)
  vid: 2

  # Combination campaign specification
  cmb_camp: R03

  # Combination solution type identifier
  cmb_sol: GRE

  # outlier removal (assess) settings
  assess:

    # satellite rms test (auto/manual/strict)
    sat_rms_tst: auto

    # coefficient for auto satellite rms test
    coef_sat: 470.0

    # threshold for manual satellite rms test for each satellite system (mm)
    thresh_sat:
      G: 15.0
      R: 25.0
      E: 15.0
      C: 50.0
      J: 100.0

    # maximum number of outlier satellite rms for a center in order to keep
    # being weighted
    max_high_satrms: 5

    # transformation parameters test (auto/manual/strict)
    trn_tst: strict

    # manual transformation thresholds for translation (mm), rotation (mas)
    # and scale (ppb)
    thresh_trn: [null,0.3,null]

    # test for minimum number of centers for each satellite (strict/eased)
    numcen_tst: eased

    # minimum number of centers for each satellite
    min_numcen: 1

    # maximum number of iterations for outlier removal
    max_iter: 100


# clock combination configs
clocks:

  # Analysis center contributions
  ac_contribs:

    # weighted centers:
    weighted:
      systems:
        COM: [G,C,J]
        GFM: [G,C,J]
        JAM: [  R,E,C,J]
        SHM: [G,  E,  J]
        TUM: [G,R,E,C,J]
        WUM: [G,R,E    ]
        EMR: [G        ]
        EMX: [  R      ]
        ESA: [G,R      ]
        IAC: [  R      ]
        JPL: [G        ]
        MCC: [  R      ]
        MIT: [G        ]
        NGS: [G        ]
        SIO: [G        ]
      prns:
        JAM: [G04]
        GFM: [E01]
      svns:
        SHM: [R701,G048]
        GFM: [E211]

    # unweighted centers (for comparison only)
    unweighted:
      systems:
        COD: [G        ]
        COX: [  R      ]
        GFZ: [G,R      ]
        GFM: [R]
        IGL: [R]
        IGS: [G,E]
        IGR: [G]
      prns:
        JAM: [G04,G28]
        GFM: [E03]
      svns:
        GFM: [E214]

    # excluded centers
    excluded:
      systems:
        COX: [R]
        GFM: [C]
      prns:
        GFM: [J01,J02]
      svns:
        GFM: [E211]

