# Configuration file in YAML format
#
#
# Processing configs
process:
  
  # verbose mode (INFO/DEBUG)
  verbose: INFO

# campaign specifications
campaign:

  author: 'IGS AC Coordinator'
  contact: 'acc@igs.org'
  
  # solution (ULT/RAP/FIN)
  sol_id: ULT
  
  # Campaign/Project specification
  camp_id: TST
  
  # Combination name/abbreviation (3 characters)
  cmb_name: IGS

  # Combination version/solution identifier (0 to 9)
  vid : 0

  # root directory for AC submissions
  subm_rootdir: /data/acc_data/ac_subm/ultra

  # root directory for saving the products
  prod_rootdir: /data/acc_combi/test/products

  # path to satellite metadata file
  sat_metadata_file: /data/acc_data/metadata/igs_satellite_metadata.snx

  # Earth orientation paramaters (EOP) source format
  # (IERS_EOP14_C04/IERS_EOP_rapid/IGS_ERP2)
  eop_format: IERS_EOP_rapid

  # path to the EOP data
  eop_file: /data/acc_data/erp/finals.daily

  # Root directory for reference frame combination summary files
  # Needed for reference frame alignment
  #rf_rootdir: /data/repro3/sinex

  # Reference frame summary file name identifier
  #rf_name: IGS1R03SNX

  # nanu summary file
  nanu_sumfile: /data/acc_data/metadata/nanus_sum.2024

  ac_acronyms:
      COD: "Center for Orbit Determination in Europe (CODE)"
      EMR: "Natural Resources Canada (NRC)"
      ESA: "European Space Agency"
      GFZ: "GeoForschungsZentrum Potsdam"
      GRG: "Centre National d'Etudes Spatiales (CNES/CLS)"
      JGX: "Geospatial Information Authority of Japan (GSI) and the Japan Aerospace Exploration Agency (JAXA)"
      JPL: "Jet Propulsion Laboratory"
      MIT: "Massachusetts Institute of Technology"
      NGS: "NOAA/National Geodetic Survey"
      SIO: "Scripps Institution of Oceanography (SIO)"
      TUG: "Graz University of Technology"
      USN: "The United States Naval Observatory (USNO)"
      UXV: "USNO experimental GPS+GLONASS"
      WHU: "Wuhan University"
      BRD: "IGS Broadcast products"
      IGC: "24-hour set of 4-10 hour predictions from the IGS Real-Time Service"
      IGU: "IGS (GPS-only) ultra-rapid operational product"
      IGV: "IGS (GPS+GLONASS) ultra-rapid experimental product, with GPS sourced from the IGS operational combination"
      IGR: "IGS (GPS-only) rapid operational product"
      IGF: "IGS final operational orbit product"
      IG2: "IGS second reprocessing (repro2) orbit product"
      IG3: "IGS repro3 GPS-only orbit product by legacy software"
      IGQ: "IGS repro3 multi-GNSS 15-minute orbit product"

# Orbit combination configs
orbits:

  # Analysis center contributions
  ac_contribs:

    # weighted centers:
    weighted:
      systems:
        COD: [G,R,E]
        EMR: [G,R]
        ESA: [G,R]
        GFZ: [G,R,E]
        GRG: [E]
        WHU: [G,R,E]
      prns:
      svns:

    # unweighted centers (for comparison only)
    unweighted:
      systems:
        #BRD: [G]
        GRG: [G]
        JGX: [G,R,E]
        SIO: [G]
        USN: [G]
        #WHU: [E]
        IGV: [G,R]
      prns:
      svns:

    # excluded centers
    excluded:
      systems:
      prns:
      svns:
  
  # sampling rate (integer in seconds)
  sampling: 300

  # center weighting method (global/by_constellation/by_block/by_sat)
  cen_wht_method: by_sat

  # satellite weighting method (RMS_L1)
  sat_wht_method: RMS_L1

  # Transform orbits to a same reference frame?
  # [Translations,Rotations,Scale]
  rf_align: [False,False,False]

  # UT1 differences applied as Z rotations
  # The ERP apriori and observed files for any center listed below must be
  # presented at rf_rootdir specified above with the long filename formats
  # {CEN}{V}{SOL}APR_{YYYYDDDHHMM}_{LEN}_{SMP}_ERP.ERP and
  # {CEN}{V}{SOL}OBS_{YYYYDDDHHMM}_{LEN}_{SMP}_ERP.ERP
  ut1_rot: []

  # remove DV maneuvering satellites
  rm_dv: True

  # exception for removing DV maneuvering satellites
  no_rm_dv: [IGV]

  # outlier removal (assess) settings
  assess:

    # satellite rms test (auto/manual/strict)
    sat_rms_tst: auto

    # satellite rms test for unweighted centers (auto/manual/strict)
    # Note: depending on how bad the unweighted centers are, having 
    # sat_rms_tst_unweighted on could result in long running time
    # (e.g. if all the satellite solutions for an unweighted center
    # are very bad, which means at least 5 iterations for removing
    # the top five sats, assuming max_high_satrms is 5)
    #sat_rms_tst_unweighted : auto

    # coefficient for auto satellite rms test
    coef_sat: 470.0

    # threshold for manual satellite rms test for each satellite system (mm)
    thresh_sat:
      G: 15.0
      R: 25.0
      E: 15.0
      C: 50.0
      J: 100.0

    # maximum number of outlier satellite rms for a center in order to keep
    # being weighted
    max_high_satrms: 5

    # transformation parameters test (auto/manual/strict)
    trn_tst: strict

    # manual transformation thresholds for translation (mm), rotation (mas)
    # and scale (ppb)
    thresh_trn: [null,0.3,null]

    # test for minimum number of centers for each satellite (strict/eased)
    numcen_tst: eased

    # minimum number of centers for each satellite
    min_numcen: 1

    # maximum number of iterations for outlier removal
    max_iter: 100

  # SP3 header information
  sp3_header:

    # coordinate system
    coord_sys: IGS20

    # information to put into the comments

    # combination type
    cmb_type: ULTRA RAPID

    # clock source
    clk_src: COD

    # antex file
    antex: IGS20_2290

    # ocean tide model
    oload: FES2014b


# clock combination configs
clocks:

  # Analysis center contributions
  ac_contribs:

    # weighted centers:
    weighted:
      systems:
      prns:
      svns:

    # unweighted centers (for comparison only)
    unweighted:
      systems:
      prns:
      svns:

    # excluded centers
    excluded:
      systems:
      prns:
      svns:

